### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by fabriciodanioj** [fabriciodanioj/latestPrice#2]
# Tasks about LatestPrice
- [ ] Draw a panel to enter the data
- [ ] Make data request
- [ ] Insomnia testing
- [ ] Creation of unit and integration tests
